### ISSUE TITLE
Sidebar doesn't show individual entries when it is collapsed

### ISSUE THREAD

**Issue by arbulu89** [trento-project/trento#128]
The sidebar doesn't behave properly when it is collapsed. It always shows the `home` entry, even though you put the mouse over any other entry.

![image](https://user-images.githubusercontent.com/36370954/124472689-b4a1b580-dd9e-11eb-84e0-0b93d5ac5bc1.png)

**Comment by rtorrero** [comment]
@arbulu89 solved in PR #131 and (embarrassingly) in PR #133
