### ISSUE TITLE
Cluster view does not show the correct status after a Failover

### ISSUE THREAD

**Issue by diegoakechi** [trento-project/trento#141]
In case a HANA failover occurs, the former secondary becomes the new master and the nodes switches roles. The new Cluster view is not presenting the correct information after such event:

The HANA secondary sync state presents an empty green box (while the SR is not enabled):

![image](https://user-images.githubusercontent.com/8420718/125629828-221311be-d89c-4798-a64f-1d9b5834037b.png)

Also, both nodes presents itself as primary (when only HANA 2 is the real primary)
![image](https://user-images.githubusercontent.com/8420718/125629938-4435f65f-6501-4ff0-a26f-b5b4cdd64b62.png)

The Virtual IP also gets moved to the secondary node, so the vIP information should be shown correctly:

![image](https://user-images.githubusercontent.com/8420718/125630157-2e1384d1-65a2-4d7f-86c0-31340aecebfa.png)

**Comment by fabriziosestito** [comment]
Closing, split in #153 and #154
