### ISSUE TITLE
Fix remediation text and references of Test/Check 1.1.6

### ISSUE THREAD

**Issue by lee-martin** [trento-project/trento#176]
https://github.com/trento-project/trento/blob/e70765b81566f41a1b0f2df86916e8f96a851bcd/examples/generic-azure.yaml#L159-L194

Please update the remediation text to describe how to set the cluster to use UCAST. The SUSE Best Practice already acknowledges the need to stop the cluster for this, see section 9.1.3 https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/   Potentially these steps may already be described in SLE-HA documentation, so we could add a reference to that.

We should also be referencing the SUSE Best Practice in the references.

(SUSE internally this is CFSA-133)

**Comment by arbulu89** [comment]
Closed at: https://github.com/trento-project/trento/pull/225
