### ISSUE TITLE
Cloud Metadata Discovery fails when using dmidecode

### ISSUE THREAD

**Issue by diegoakechi** [trento-project/trento#194]
VMs running on Azure will report `Microsoft Corporation` in case they are running on Hyper-V virtualization, what might not be the case all the time. 

Some users reports the following output on the dmidecode of their VMs that makes the Cloud Discover fail:

```~ # dmidecode -s bios-vendor
American Megatrends Inc.
```

With that, the safest way would be to use the Azure INstance Metada web service to confirm that the machine is really running on an Azure environment.

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/instance-metadata-service?tabs=linux

As this is always a local call inside the VM (even that REST API), it should respond very fast not affecting the discovery time.

That said, it is important to make sure the discovery will not hang waiting for a long timeout in case the machine is not running on Azure, where the metadata API is not available.

**Comment by petersatsuse** [comment]
MSFT provided us the command already to find out if its Azure or not for saptune last year.

To figure out whether it Is Azure VM, you can use below command: 

# dmidecode -s chassis-asset-tag
7783-7084-3265-9085-8269-3286-77

The result is ASCII encoded. When convert to a string, the following string shows up: MSFT AZURE VM
