### ISSUE TITLE
Cluster nodes disappearing from the cluster list when HA discovery loop fails

### ISSUE THREAD

**Issue by rtorrero** [trento-project/trento#205]
This is because the metadata gets overwritten with incomplete data probably when some of the scripts we use in the background to collect information fails.

The other nodes will post information about the failing node belonging to the cluster while the discovery of the failing node will not write it, creating a discrepancy between both.

Which information should we present to the end user? The configuration that shows that the node supposedly belongs to the cluster or the discovery information that shows it does _not_ belong to the cluster?

**Comment by arbulu89** [comment]
Closing this ticket as the implementation has been moved from consul to a postgres based database.
