### ISSUE TITLE
Remove the discovery TTL consul health checks

### ISSUE THREAD

**Issue by stefanotorresi** [trento-project/trento#208]
We are misusing the Consul Health Check functionality to register a bunch of TTL checks which are not actually needed.

We can supersede these with a single `trento-agent` health check reporting the status of the agent itself (instead of the result of the HA Configuration Checks, which is going to be run by the Runner component instead).

Related to #89

**Comment by fabriziosestito** [comment]
@stefanotorresi what should the `Trento Health` check depend on?

**Comment by stefanotorresi** [comment]
> @stefanotorresi what should the `Trento Health` check depend on?

Well, my idea would be that if any of the discovery loops fails, than this single check fails with some output about the specific error that occurred.
IOW I would like all the Consul health checks that we currently have for the discovery loops consolidated under a single one.

That said, if you have other ideas on how to self-check the Trento Agent, I'm all ears!

**Comment by fabriziosestito** [comment]
@stefanotorresi I have a PR ready for this, just holding it after the runner branch merge, i basically did what you just described but changed a little bit when the discoveries return errors (e.g. no error if nothing is discovered, just a negative result)
