### ISSUE TITLE
Change the "HA Config Checker" Consul health check into a Trento Agent health check.

### ISSUE THREAD

**Issue by stefanotorresi** [trento-project/trento#209]
We are currently misusing the Consul health check functionality. Since the "HA Config Checker" now lives in a separate, centralized component, the related Consul health check needs to be changed in semantic, and instead become a health check about the Trento Agent itself, rather than about the user's workload.

This is related to #208, as in the discovery loops can be removed and all the errors occurring within the Trento Agent should be reported as an output of a single "Trento Agent" Health Check.

IOW, we need to rename the "HA Config Checker" Consul Health check into "Trento Agent" and change its output and error statuses, from being generated by the old HA Config Checker (which is going to be removed from the Trento Agent component), to being generated by all the internal Agent goroutines, like the the discovery loops.

**Comment by arbulu89** [comment]
@stefanotorresi To be on the exact same page, I understand this as the current checker is completely removed from the Agent side, and the new runner result is not reported to the agents. The web app will get the runner results (the cluster results by now) from the runner component (ARA).
Correct?

**Comment by stefanotorresi** [comment]
> @stefanotorresi To be on the exact same page, I understand this as the current checker is completely removed from the Agent side, and the new runner result is not reported to the agents. The web app will get the runner results (the cluster results by now) from the runner component (ARA).
> Correct?

Yes!
