### ISSUE TITLE
root user hardcoded in deploy.sh

### ISSUE THREAD

**Issue by lee-martin** [trento-project/trento#214]
https://github.com/trento-project/trento/blob/main/hack/deploy.sh#L11

Hi,

After struggling to make my own deploy script I discovered deploy.sh hidden under the "hacks" directory. Can you please add references to using this script on the main trento page, since deploying easily is important for users.

Now to a problem I have running the script:

As per https://github.com/trento-project/trento/blob/main/hack/README.md I'm passing in my "cloudadmin" user like this "./deploy.sh cloudadmin@137.116.197.204 deploy-web" , however this results in the following errors (I removed my IP):

"
Checking if process trento is running in cloudadmin@<IP>...
root@cloudadmin@<IP>: Permission denied (publickey).
Checking if process consul is running in cloudadmin@<IP>..
root@cloudadmin@<IP>: Permission denied (publickey).
..
"

It seems the script is not parsing the username I'm passing on the commandline. As a workaround, I replaced "root" with my "cloudadmin" user in the script, which got ssh connections to work.

thanks

**Comment by stefanotorresi** [comment]
possibly made invalid by #152

**Comment by stefanotorresi** [comment]
> possibly made invalid by #152

Confirmed. This `deploy.sh` script is actually not meant to be used by end-users.
