### ISSUE TITLE
non-root users don't have write permissions on /srv by default

### ISSUE THREAD

**Issue by lee-martin** [trento-project/trento#215]
https://github.com/trento-project/trento/blob/main/hack/deploy.sh#L37-L38

The above code lines result in the following error on my clean SLES deployment when deploying with non-root user "cloudadmin"
```
./deploy.sh <IP> deploy-web
Checking if process trento is running in <IP>...
Checking if process consul is running in <IP>...
mkdir: cannot create directory ‘/srv/trento/’: Permission denied
mkdir: cannot create directory ‘/srv/consul’: Permission denied
```

Looking on the SLES system I want to deploy to, non-root users don't have write permissions on /srv by default

```
cloudadmin@TrentoServer:~> ll -d /srv
drwxr-xr-x 6 root root 54 Jun  4 09:51 /srv
```

I guess this could be fixed by adding sudo for non-root users, the same as with the agent-deploy option?

**Comment by stefanotorresi** [comment]
possibly made invalid by #152

**Comment by stefanotorresi** [comment]
> possibly made invalid by #152

Confirmed. This `deploy.sh` script is actually not meant to be used by end-users.
