### ISSUE TITLE
suggestion for the logo :)

### ISSUE THREAD

**Issue by napo** [trento-project/trento#231]
I realize that I am OT with respect to the project.
I really appreciated the choice of the name because I live in Trento.
I suggest you to change the logo by using some relevant monuments of the city:
- [Castello del Buonconsiglio](https://it.wikipedia.org/wiki/Castello_del_Buonconsiglio) (= "castle of the good advice")
![](https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/20110727_Trento_Buonconsiglio_Castle_6609.jpg/320px-20110727_Trento_Buonconsiglio_Castle_6609.jpg)
or
- the [fountain of Neptun](https://it.wikipedia.org/wiki/Fontana_del_Nettuno_(Trento)) in the main square
![](https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Trento_Piazza_del_Duomo_Fontana_del_Nettuno_13.jpg/345px-Trento_Piazza_del_Duomo_Fontana_del_Nettuno_13.jpg)
or ... if you like to use towers and green
- the [Torre Verde](https://it.wikipedia.org/wiki/Torre_Verde) (= "the green tower")
![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Trento-Torre_Verde_from_S.jpg/360px-Trento-Torre_Verde_from_S.jpg)
This is a issue only for fun and to appreciate your choice with the name 

if you like I can try to sketch a logo inspired of these monuments... in any case you can forgot / delete this issue

**Comment by stefanotorresi** [comment]
Hey @napo, thank you very much for your input; we already have a logo, and it was very much influenced by Trento landmarks as you just suggested! 😃 

![trento logo](https://raw.githubusercontent.com/trento-project/trento/main/web/frontend/images/trento-logo-stacked.png)

We should probably put this in the readme, though!
