### ISSUE TITLE
CI: Deployment on monitoring node fails due to missed trento-runner.service file

### ISSUE THREAD

**Issue by rtorrero** [trento-project/trento#254]
When deploying to a clean cluster using the CI, the deployment on `vmmonitoring` node fails as it can't find the `trento-runner.service` file.

We need to add the installation of the file to the provision.sh script

**Comment by rtorrero** [comment]
Problematic code:
```
    - name: stop trento runner
      run: |
        if [ "${{ inputs.role }}" = "web" ]; then
          systemctl stop trento-runner
        fi
      shell: bash
      ```

**Comment by stefanotorresi** [comment]
superseded by #269
