### ISSUE TITLE
Trento RPM built in devel:sap:trento is not being injected the version number correctly

### ISSUE THREAD

**Issue by stefanotorresi** [trento-project/trento#262]
The binary built in this package: https://build.opensuse.org/package/show/devel:sap:trento/trento

Has the following behaviour:
```
> trento version
Trento version 0
built with go1.16.5 linux/amd64
```

The expected version number should instead match the RPM version, which currently is `0.4.0+1630926451.42dff2b`

**Comment by aleksei-burlakov** [comment]
The fix is proposed in #265
