### ISSUE TITLE
Make database-dependant tests skippable.

### ISSUE THREAD

**Issue by stefanotorresi** [trento-project/trento#364]
The DX currently suffers a bit due to the recently introduced requirement to run the full development environment in an actual kubernetes cluster just to deploy a postgresql instance to run tests against.

I suggest to introduce some mechanism, either an environment variable or a test pre-flight check (e.g. try to connect with a very short timeout, and skip the test if connection failed), which allows to skip tests when an actual database instance is not immediately available.

**Comment by fabriziosestito** [comment]
The only way i am aware of is using `t.Skip` + env variable but it needs changing the tests.
AFAIK build flags can be used to run only certain type of tests but not skipping it.
