### ISSUE TITLE
Improvements in the runner logging

### ISSUE THREAD

**Issue by arbulu89** [trento-project/trento#469]
The runner debugging is being an issue, specially because it doesn't log until the ansible execution is finished, and 2nd, because the ansible logs are set to debug.

In order to improve this:
- Log the ansible logs as they happen
- Increase the ansible output logs severity to `info`

**Comment by stefanotorresi** [comment]
> * Log the ansible logs as they happen

Yes! You read my mind there. I think we should be able to hook the `exec.Command` stdout interface to the logger and have the command stream its output directly as Trento console log lines.
