### ISSUE TITLE
Console - Home - SAP System

### ISSUE THREAD

**Issue by Zaoliang** [trento-project/trento#474]
The content should be a little bit more about or provide link for information like: SAP System Idenfication
or `PRD`, `DEV`, or `QAS`.

Feature request: add proper information or links for these definitions

**Comment by stefanotorresi** [comment]
@Zaoliang I appreciate the work you're doing but I'm a bit at a loss here. `PRD|DEV|QAS` are user-generated: those are conventional names that SAP system administrators often use to identify their systems. There is nothing in Trento code about these names, so I don't think we can establish any "proper information" about them.
