### ISSUE TITLE
'Select All' and 'Deselect All' are missing in Filters 'Health status...'

### ISSUE THREAD

**Issue by Zaoliang** [trento-project/trento#476]
Home - Hosts - Filters 

Here user can select each status, SAP System, Tags, but 'Select All' and 'Deselect All' are missing in Filters 'Health status...'

**Comment by abravosuse** [comment]
Replicated in v0.6.0 (cycle 2). Given that in the Health Section only three values are possible (Passing, Warning, Critical) having Select / Deselect All doesn't help much. Low priority.,

**Comment by arbulu89** [comment]
Hey @abravosuse ,
Do we still want to implement this?
It is super easy to do from the tech standpoint

**Comment by abravosuse** [comment]
Not in my opinion @arbulu89. It's just three values to select from: select all, deselect all won't make a big difference.

**Comment by arbulu89** [comment]
Closing them
