### ISSUE TITLE
use border line for input field

### ISSUE THREAD

**Issue by Zaoliang** [trento-project/trento#477]
Feature request:
Home - Hosts - Filters 
border line looks nice and gives user hints to move mouse for input there.

**Comment by stefanotorresi** [comment]
I'm not quite clear: are we deviating from the EOS design system WRT to form inputs? We're just implementing those styles.

**Comment by abravosuse** [comment]
Reproduced in v0.6.0 (cycle 2). For me the input boxes are quite easy to distinguish. And I like the fact the box borders highlight when you hover over them. In my opinion there is no need for this enhancement. Issue can be closed.
