### ISSUE TITLE
cannot detect cluster type for drbd_cluster and netweaver_cluster

### ISSUE THREAD

**Issue by Zaoliang** [trento-project/trento#480]
see http://13.95.71.67/clusters

Under Cluster type shows 'Unknown' 
Click and open cluster name for example:
http://13.95.71.67/clusters/488f371139960e782f3e585cb2900f74
or
http://13.95.71.67/clusters/2ecaf0b26c14875584f4d632b060f4a7

At moment  it can detect type 'HANA scale-up'

**Comment by stefanotorresi** [comment]
That's by design: we currently don't detect any specific type of HA clusters other than HANA.
S4/HANA / Netweaver are in a couple of months down in the roadmap.
