### ISSUE TITLE
cannot detect hosts status correctly or returns 500 error code

### ISSUE THREAD

**Issue by Zaoliang** [trento-project/trento#482]
open http://13.95.71.67/sapsystems
3 SAP environments are up and running. 
I observed that Trento returns the following issue:

open host with red status: for example: http://13.95.71.67/hosts/vmnwdev01
scroll down and check Trento Agent status: everything is okay, passing

But I see http://13.95.71.67/hosts/vmnwqas04 with critical status:

No HA cluster discovered on this host
Error while running discovery 'sap_system_discovery': could not lock the kv for sapsystem: failed to create session: Unexpected response code: 500 (rpc error making call: apply failed: Check 'serfHealth' is in critical state)
Error while running discovery 'cloud_discovery': could not lock the kv for cloud data: failed to create session: Unexpected response code: 500 (rpc error making call: apply failed: Check 'serfHealth' is in critical state)
Error while running discovery 'subscription_discovery': could not lock the kv for cloud data: failed to create session: Unexpected response code: 500 (rpc error making call: apply failed: Check 'serfHealth' is in critical state)
Host with name: vmnwqas04 successfully discovered

**Comment by abravosuse** [comment]
Related probably to this issue, I would like to add the following: the status of the hosts in the Hosts view of the QA Trento Console (http://13.95.71.67/hosts) is ever changing from Passing to Critical and vice versa. One moment you have 10 hosts in critical status, the next one you have 13, the next one 7. 

Then, as Zaoliang mentions above, when you go and click on a host in critical status, sometimes no errors are shown (agent in passing status) sometimes the aforementioned 500 errors are displayed.

**Comment by arbulu89** [comment]
@abravosuse This most of the times happens because the used discovery time is to low, and the writing time takes a long time.
As a counter measurement lowering the discovery times in the agents just works on this.
Anyway, this is due `consul`. The "non consul" current implementation shouldn't have this behaviour. 
This PR might have the fix already: https://github.com/trento-project/trento/pull/517

**Comment by abravosuse** [comment]
@arbulu89 I'm guessing PR #517 will be part of v0.7.0, is that correct? Until that, we can try the workaround you propose. I understand you can do this by using flag --discovery-period. Questions:

- Is the value specified in seconds?
- What is the default value?
- How do I enable this flag if I'm launching the agent with systemd (sudo systemctl enable --now trento-agent)

Thx!

@Zaoliang let's take this into account when running the tests in round 2.

**Comment by arbulu89** [comment]
> @arbulu89 I'm guessing PR #517 will be part of v0.7.0, is that correct? Until then, we can try the workaround you propose. I understand you can do this by using flag --discovery-period. Questions:
Yes, it will be included in 0.7.0
> 
>     * Is the value specified in seconds?
No, it is specified in minutes
> 
>     * What is the default value?
The default value is 2 minutes. It should be safe enough, but we could increase it to something like more 5 minutes to be more conservative
> 
>     * How do I enable this flag if I'm launching the agent with systemd (sudo systemctl enable --now trento-agent)

You will need to change the configuration file placed at `/usr/etc/trento/trento.yml` or `/etc/trento/trento.yml` and include the `discovery-period: 5` entry (5 being 5 minutes loop)

**Comment by abravosuse** [comment]
2nd testing cycle (v0.6.0): host status seems to be much more stable under this version (without having touched the discovery period).

**Comment by fabriziosestito** [comment]
Closed, consul-related
