### ISSUE TITLE
Trento Agent version name should be consistent

### ISSUE THREAD

**Issue by Zaoliang** [trento-project/trento#490]
See http://13.95.71.67/hosts?trento-sap-systems=HDP&trento-sap-systems=HDQ&trento-sap-systems=NWD

I found v0.5.0+git.dev53.1634912175.8b24afd and v0.5.0

**Comment by abravosuse** [comment]
Just another way to reproduce this error:

1. Open the QA Trento Console URL (http://13.95.71.67/)
2. Click on Hosts in the Menu section (or in the "Go to view" link in the Hosts section)
3. Review column Agent version for the listed hosts: you will see that sometimes the version name comes as v0.5.0, sometimes as v0.5.0+git.dev53.1634912175.8b24afd

**Comment by abravosuse** [comment]
2nd test cycle (v0.6.0): Agent version name is v0.6.0 in all hosts. It seems this issue has already been addressed somewhere else. Can you please confirm? Thx!

**Comment by Zaoliang** [comment]
http://20.67.108.123/about shows v0.6.0

but if you check http://demo.trento-project.io/about
you find Web version v0.6.0+git.dev181.1639398368.3a8993f
Since this is latest version of trento server, I won't think this issue got fixed finally so far.

**Comment by abravosuse** [comment]
v0.7.0: agent version displayed as v0.7.0 in all agent hosts. Issue can be closed.
