### ISSUE TITLE
Tilde is not correctly resolved on installation script

### ISSUE THREAD

**Issue by tomschr** [trento-project/trento#492]
# Situation

After I've created a public SSH key, I've started the installation script with:

```
curl -sfL https://raw.githubusercontent.com/trento-project/trento/main/install-server.sh | bash
```

After I've entered the private SSH key, I got this error messages:

```
Please provide the path of the runner private key: ~/.ssh/id_rsa
Installing trento-server on k3s...
Installing K3s...
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
Installing Helm...
Updating Helm dependencies...
Installing trento-server chart...
Release "trento-server" does not exist. Installing it now.
Error: failed parsing --set-file data: open ~/.ssh/id_rsa: no such file or directory
```

However, the file is there.

# Suggestion

It seems, the tilde isn't correctly resolved in the script. I would suggest to support this use case. In my case, `~` should be resolved to `/home/cloudadmin`.

**Comment by dottorblaster** [comment]
Hi @tomschr, thanks for reporting this! Actually, I think this is by design, because Helm doesn't match really well with relative paths and stuff like tilde.

@stefanotorresi do you think we could improve the readme with an explicit statement about that?

**Comment by tomschr** [comment]
Thank you Alessio @dottorblaster for your answer!
I'm not talking about relative paths. That's okay if that is out of scope. However, a tilde wouldn't count as relative. :wink: It wouldn't be difficult to resolve the tilde in the script before Helm sees it.

**Comment by dottorblaster** [comment]
Well if it wouldn't be difficult we always accept pull requests and encourage folks to submit them :smile: 

Anyway, we'll keep an eye on this and have a look as soon as possible, thanks!

**Comment by fabriziosestito** [comment]
@tomschr thanks for reporting this! 
@dottorblaster  Even if it is true that this is a Helm constraint, the user shouldn't care about that, since we wrapped it inside an installer script.
Of course we will be glad to accept a PR for this!

**Comment by tomschr** [comment]
Thanks @fabriziosestito I completely agree, the user/customer shouldn't care. It should be completely done in the script. As tilde is a valid path, we should support it (and it would be really strange if we wouldn't do that).

I've created a PR a minute ago, see #494 for details. :slightly_smiling_face:
