### ISSUE TITLE
Bad Gateway error when navigating through the different views in the console

### ISSUE THREAD

**Issue by abravosuse** [trento-project/trento#502]
This error has been noticed in the test environment that has been set up for the QA Team. The environment consists of 3 x SAP NetWeaver 7.5 on HANA systems, with HA at application and database level. Details on the environment can be found at https://confluence.suse.com/display/SAP/SAP+landscape+for+Trento+testing+in+Azure.

How to reproduce the error:

1. Open the QA Trento Console URL.
2. Go to the Clusters view.
3. Then to the HANA Databases view.
4. Then to the SAP Systems view.
5. And so on until, eventually, the bad gateway error is issued.

Should you need OS access to analyze this error, please let me know and I will provide you with the required ssh key.

**Comment by Zaoliang** [comment]
Typo in issue titel: should be Bad Gateway,
This performance/network issue is a major issue and it makes user nearly impossible to check HANA Databases.

**Comment by stefanotorresi** [comment]
@abravosuse @Zaoliang could any of you please report the logs of the `trento-server-web` deployment right after the occurrence of the error?
Should be as easy as `kubectl logs deployments/trento-server-web`.

**Comment by abravosuse** [comment]
@stefanotorresi command `sudo kubectl logs deployments/trento-server-web` returns the following:
`Error from server (NotFound): deployments.apps "trento-server-web" not found`
I'm running the command from `/home/cloudadmin`. Do I need to run it from an specific location?

**Comment by abravosuse** [comment]
@arbulu89 @stefanotorresi just a follow up on this topic. We are working on cycle #2 and seeing the same issue. How should I run this command? Thank you!

**Comment by rtorrero** [comment]
@abravosuse I think the deployment name is different on your k3s deployment, let's debug this together on slack

**Comment by abravosuse** [comment]
I sit down with @rtorrero and manage to run the `sudo kubectl logs deployments/trento-server-web` command successfully.  We reproduce the bad gateway error in the console (now under version 0.6.0). Then I provide @rtorrero with the ssh key and public IP of the Trento Server so that he can logon and analyze the logs.

**Comment by rtorrero** [comment]
We are getting:

```
2021/12/13 10:24:09 [Recovery] 2021/12/13 - 10:24:09 panic recovered:
GET /clusters HTTP/1.1
Host: 20.67.108.123
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,es;q=0.8
Cookie: session=MTYzOTM5MDgzOHxEdi1CQkFFQ180SUFBUkFCRUFBQUJQLUNBQUE9fPD1uCBDLQBnZ6DjGhquZRi7a_cbY1DRh7npW1zgLJKI
Referer: http://20.67.108.123/clusters/7c0267f26a2b0250ffa7f1fd5b755638
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
X-Forwarded-For: 10.42.0.1
X-Forwarded-Host: 20.67.108.123
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: traefik-6b84f7cbc-w9fzp
X-Real-Ip: 10.42.0.1


write tcp 10.42.0.8:8080->10.42.0.17:41310: i/o timeout
github.com/gin-gonic/gin@v1.7.0/context.go:916 (0xaf92db)
github.com/gin-gonic/gin@v1.7.0/context.go:925 (0xaf9398)
github.com/trento-project/trento/web/clusters.go:352 (0xdf9b59)
github.com/gin-gonic/gin@v1.7.0/context.go:165 (0xbfcd35)
github.com/gin-contrib/sessions@v0.0.3/sessions.go:52 (0xbfcd1d)
github.com/gin-gonic/gin@v1.7.0/context.go:165 (0xdf0a32)
github.com/trento-project/trento/web/errors.go:10 (0xdf0a12)
github.com/gin-gonic/gin@v1.7.0/context.go:165 (0xb08ff9)
github.com/gin-gonic/gin@v1.7.0/recovery.go:99 (0xb08fe0)
github.com/gin-gonic/gin@v1.7.0/context.go:165 (0xdfdcd0)
github.com/trento-project/trento/web/logger.go:13 (0xdfdc92)
github.com/gin-gonic/gin@v1.7.0/context.go:165 (0xaff6c9)
github.com/gin-gonic/gin@v1.7.0/gin.go:489 (0xaff6af)
github.com/gin-gonic/gin@v1.7.0/gin.go:445 (0xaff19b)
net/http/server.go:2867 (0x74a2c2)
net/http/server.go:1932 (0x7456ec)
runtime/asm_amd64.s:1371 (0x46cc80)

[GIN-debug] [WARNING] Headers were already written. Wanted to override status code 200 with 500
```

Is this still relevant @stefanotorresi or is this potentially fixed already by some of the newer commits to rolling? I don't seem to be able to reproduce it in our demo environment.

@abravosuse also says that the more clusters that are added to trento, the higher the chance is to get this sporadic issue while refreshing `/clusters`

**Comment by arbulu89** [comment]
@rtorrero Can you confirm the version of the agents and web?
I accessed the web and it says `0.6.0`. This version still uses consul, so this error is expected. The new version 0.7.0 will be free of consul from our side, so this issue woudln't be there anymore

**Comment by rtorrero** [comment]
@arbulu89 yes, this is still from 0.6.0 and I also assumed that it was a consul-related thing but wanted someone else to double check just in case. Let's keep it open until we release and close it then. Thanks!

**Comment by fabriziosestito** [comment]
Timeouts should be solved by the consul removal
