### ISSUE TITLE
Unknown host listed in Hosts view

### ISSUE THREAD

**Issue by abravosuse** [trento-project/trento#503]
This issue has been noticed in the test environment that has been set up for the QA Team.

How to reproduce the error:

1. Open the QA Trento Console URL. 
2. Click on Hosts in the Menu section (or in the "Go to view" link in the Hosts section)
3. Review the status of the listed hosts: host trentoserver with IP address 10.42.0.9 doesn't exist in QA environment but shows up in list.

**Comment by stefanotorresi** [comment]
That's indeed something that has been on my backburner for ages. It only takes a host tag and a filter in the Consul catalog query to fix it, but we always neglected to do that.
This problem will be fixed once we remove Consul completely, but let's keep this open in case we need to act on this before the soft launch.

**Comment by fabriziosestito** [comment]
Solved by consul removal
