### ISSUE TITLE
Cluster view: Health section not showing clusters in any status

### ISSUE THREAD

**Issue by abravosuse** [trento-project/trento#506]
This issue has been noticed in the test environment that has been set up for the QA Team.

How to reproduce the error:

1. Open the QA Trento Console URL.
2. Click on Pacemaker Clusters in the Menu section (or in the "Go to view" link in the Pacemaker Clusters section)
3. Filter by Cluster type = HANA scale-up: three HANA scale-up clusters are shown.
4. Review the Health section on top: there are 0 clusters in Passing status, 0 clusters in Warning status and 0 clusters in Critical status.

**Comment by arbulu89** [comment]
@abravosuse I don't see any error here.
We deliberately didn't put the `unknown` (grey) state in the Health boxes on top, that's why we don't have any value there.
In this case at least, we don't have any errorer, warning or passing cluster (as the duplicated name thing doesn't count).

**Comment by abravosuse** [comment]
@arbulu89 This is what I see in the Pacemaker Clusters view:
![image](https://user-images.githubusercontent.com/91731013/144197584-649321ff-6d12-4ca2-85b1-89be538ec044.png)
I have two HANA scale-up clusters. Each one should have one particular Health status: Passing, Warning or Critical, shouldn't it? But I don't see it reflected in the Heath section on top.

**Comment by arbulu89** [comment]
@abravosuse This is related to this: https://github.com/trento-project/trento/issues/507

**Comment by abravosuse** [comment]
@arbulu89 then it was a miss-understanding on my side. I thought the Health section in the Pacemaker Clusters view referred to the health status of the cluster based on the return values for SAPHanaSR health state and HANA secondary sync state. I didn't think it was related to the checks verification. 

If that is the case, I guess my question is: are we supposed to see here an addition of all the checks verifications for all the registered clusters?

**Comment by abravosuse** [comment]
Thank you @arbulu89. Yes, I'll check with Lee and @stefanotorresi what sort of info makes sense to have here. In an environment with several clusters, that's aggregated value might not be very usueful.

**Comment by lee-martin** [comment]
> @arbulu89 then it was a miss-understanding on my side. I thought the Health section in the Pacemaker Clusters view referred to the health status of the cluster based on the return values for SAPHanaSR health state and HANA secondary sync state. I didn't think it was related to the checks verification.
> 
@abravosuse  Your observation is extremely valid, so please do not dismiss this as a misunderstanding. You come to trento with fresh eyes and indeed I agree from a user perspective it really confusing that the health state on this screen only reflects the aggregate results of all the individual cluster checks which are shown in the check results screens.

So what are suggesting is that the health on this screen should simply only show the number of clusters in a passing, warning or critical state? 

This means the health display would always be context dependent in that case, I'm not sure if that itself might also confuse users. What do you think?


> If that is the case, I guess my question is: are we supposed to see here an addition of all the checks verifications for all the registered clusters?

In my understanding this is what the current code does, but based on your feedback, that may no longer be the best idea.
We can discuss your points with PM and some ramp-up customers to get more feedback.

@arbulu89 and @stefanotorresi  I would like to follow-up on this issue and probably make a change, BUT from a priority perspective this can wait IMO until version 1.0 or even 1.1.  (If you would like to add a priority label to reflect that )

**Comment by abravosuse** [comment]
> So what are suggesting is that the health on this screen should simply only show the number of clusters in a passing, warning or critical state?

@lee-martin correct!

**Comment by arbulu89** [comment]
@abravosuse This is what it does. But based on the checks. With aggregated, I mean that if one cluster has 10 checks passing, 10 in warning and 10 in error, the result is error.
If there is 0 error and any warning, the result is warning.
Otherwise it will be passing.
We will have 1 value per cluster, no more.
So once the checks are passing for only 1 cluster, in that health box we will see 1 as passing.
