### ISSUE TITLE
Cluster detail view: checks selected but not showing in Health section

### ISSUE THREAD

**Issue by abravosuse** [trento-project/trento#507]
This problem has been detected in the test environment that has been set up for the QA Team.

How to reproduce the problem:

1. Open the QA Trento Console URL.
2. Click on Pacemaker Clusters in the Menu section (or in the "Go to view" link in the Pacemaker Clusters section)
3. Filter by cluster Type = HANA scale-up
4. For any listed HANA cluster, click on the cluster name or the corresponding ID.
5. In the cluster detail view, click on the Settings button next to "Pacemaker Cluster Details".
6. In the hana_cluster window that opens up:
- Leave the Connection settings section as is (user cloudadmin has been enabled to connect via ssh from Trento Server to all hosts with Trento agents)
- In the Checks selection section, select some of the available checks.
- Click Save and go back and close the hana_cluster window.
7. Back to the cluster detail view, review the Health section on the top right corner: it shows 0 Passing, 0 Warning, 0 Critical.
8. Click on <Show check results>: a Health details window opens but it lists no checks.

**Comment by abravosuse** [comment]
Step 8 above should read:
8. Click on Show check results: a Health details window opens but it lists no checks.

**Comment by arbulu89** [comment]
It looks like back again the test `2C2D43` is giving troubles and blocking the whole ansible execution...
I will have a look on how we can fix it

**Comment by arbulu89** [comment]
More information. The error only happens if the runner is executed within the container. And to make things worse, if you access the pod and execute the same exact command of the ansible-playbook or the trento runner itself, it works fine...
What a hell..

**Comment by arbulu89** [comment]
Finally, adding `tty: true` in the trento runner container declaration in the helm chart fixes the issue.
Change here: https://github.com/trento-project/trento/pull/534/commits/62857f5ff67231ff9a837b22a9bb303c46ceb466
