### ISSUE TITLE
Instance numbers with one digit in SAP system detail view

### ISSUE THREAD

**Issue by abravosuse** [trento-project/trento#508]
This issue has been detected in the test environment that has been set up for the QA team.

How to reproduce the error:

1. Open the QA Trento Console URL.
2. Click on SAP Systems in the Menu section (or in the "Go to view" link in the SAP Systems section)
3. Click on the SID of any of the listed systems.
4. Review the instance status in the Layout section: instances with numbers between 0 and 9 are showing with only one digit, but SAP naming convention says it should be two.

**Comment by diegoakechi** [comment]
Making the visualization easier 
![image](https://user-images.githubusercontent.com/8420718/143583902-7d9a05da-d750-4e31-bcc1-78759ea3ace9.png)

**Comment by stefanotorresi** [comment]
We can sure add 0 padding to these values but, for the record, we show this data as it comes from SAPControl, so apparently SAP is not consistent with their own conventions. ;)
