### ISSUE TITLE
HANA primary info missing after failover

### ISSUE THREAD

**Issue by abravosuse** [trento-project/trento#512]
This issue has been noticed in the test environment what has been set up for the QA Team. 

High level description: in one of the HANA clusters, we have stopped the primary database, waited for the secondary node to take over and checked the status of the HANA instance in the Trento Console. The detail view of the database, in the layout section, shows instance 10 in former primary node in SAPControl-GRAY status, which is correct; but there no info provided about the new primary database.

How to reproduce the error (required public IP addresses and private key for SSH connection will be provided on demand):

1. Log on vmhdbdev01:
localworkstation# ssh -i ~/.ssh/id_rsa_cloud cloudadmin@vmhdbdev01
2. Switch to user hddadm:
vmhdbdev01:cloudadmin> sudo su - hddadm
3. Gracefully stop the HANA instance:
vmhdbdev01:hddadm> HDB stop
4. Monitor failover until secondary database is promoted to primary and IP address moves to vmhdbdev02:
cloudadmin@vmhdbdev01:~> sudo crm status
5. Open the QA Trento Console URL.
6. Click on HANA Databases in the Menu section (or in the "Go to view" link in the HANA Databases section)
7. Click on HDP and review status of instance 10 in the Layout section.

**Comment by abravosuse** [comment]
As a follow up of the test described above we registered the old primary on node 01 with the new primary on node 02, recovered the cluster resources on node 01 and checked status of HANA instance in the Trento console. 

After doing this, instance 10 in node 01 (which is now secondary) shows in SAPControl-GREEN status in the layout section of the HANA detail view, which is correct. But still, there is no info provided about the new primary instance on node 02.

**Comment by arbulu89** [comment]
@stefanotorresi @lee-martin @abravosuse This issue happens in the `SAP System details` view, which we decided to "disable" for the next release until we have something more valuable. Could we remove the `prio high` label.
(and maybe even close the ticket, as the page would go to a WIP state)

**Comment by abravosuse** [comment]
mmmm I'm confused @arbulu89. This issue is specific to the HANA cluster...

**Comment by arbulu89** [comment]
> mmmm I'm confused @arbulu89. This issue is specific to the HANA cluster...

You describe to check the sap control layout, which is in the SAP System details page (or the HANA Database details page).
This is what I mean. This page is not even finished. 
Actually, I was already aware about this bad behaviour.

**Comment by abravosuse** [comment]
v0.6.0 (QA testing round 2): the issue persists.

**Comment by arbulu89** [comment]
Hi @abravosuse ,
I have re-checked this, and it looks like works fine. Maybe some of the latest changes has fixed it.
I have followed your steps. 

Keep in mind that in the layout we don't show which of the nodes is the primary or secondary. This basically by passes the output of `sapcontrol -function GetSystemInstanceList` output.

Once the primary node is stopped, and the clusters takes over we have this:
![image](https://user-images.githubusercontent.com/36370954/146347125-0de7b92a-a45f-4e7f-af76-18255a6b7eb3.png)

And after registering back:
![image](https://user-images.githubusercontent.com/36370954/146347148-413178b9-eefc-41d4-8ad5-151e06c318a5.png)
![image](https://user-images.githubusercontent.com/36370954/146347165-1653a080-45e9-4fa7-bb33-08dccf17ef29.png)

**Comment by abravosuse** [comment]
@arbulu89 we will confirm we our testing but I can tell you already that this looks great. Previously, the layout section would show only the status of the instance in node 01, and you wouldn't have any info about the instance running in node 02. Now you can see both. Great!

**Comment by abravosuse** [comment]
v0.7.0: confirmed. Issue can be closed.
