### ISSUE TITLE
Use the host identifier as host details page reference instead of the hostname

### ISSUE THREAD

**Issue by arbulu89** [trento-project/trento#521]
Right now, we use the hostname as the host details page reference to create the urls:
![image](https://user-images.githubusercontent.com/36370954/144079845-d8837f58-fc76-4f26-96e1-2a5ea0f26d4e.png)

Even though usually the hostname within an installation are unique, if we combine multiple deployment, there might be some collision there.

As we already have the host unique identifier stored in the database, we should transition to use this value.

**Comment by fabriziosestito** [comment]
Closed by the new host implementation
