### ISSUE TITLE
Provide direct navigation from the check results modal to the catalog

### ISSUE THREAD

**Issue by rtorrero** [trento-project/trento#532]
On the check results modal, when a user sees a failing test, he is probably going to be interested in the detailed and references that we provide in the checks catalog page.

![check-results-modal](https://user-images.githubusercontent.com/2668401/144410513-f4f1ef45-a3cd-4840-aa63-5deca12c783a.png)
Right now, he was to make several clicks and navigate to a different section, as well as remembering the name of the check to be able to get that information. We could instead provide a direct link to the check catalog by maybe using anchors in the catalog page?
![catalog](https://user-images.githubusercontent.com/2668401/144410524-8d7f2922-6e79-40af-b6ed-8d3c29400497.png)

We could link them from the check results page with e.g.:
`demo.trento-project.io/catalog#156F64`

Which would save the users quite a bit of interaction

**Comment by rtorrero** [comment]
thanks to @fabriziosestito for the anchor idea :-)

**Comment by lee-martin** [comment]
@rtorrero  this should be the same as https://jira.suse.com/browse/CFSA-266 ?

**Comment by rtorrero** [comment]
I think so @lee-martin though the issue in CFSA-266 doesn't specify anything about linking explicitly though I think it's the best approach!

Thanks for pointing this out, I didn't notice :-)
