### ISSUE TITLE
The icon of magnifying glass is misleading

### ISSUE THREAD

**Issue by Zaoliang** [trento-project/trento#540]
trento server: v0.6.0

The icon of magnifying glass is misleading because it shows up only about Apache License, it doesn't provide a search function.

![magnifying-glass](https://user-images.githubusercontent.com/4113246/144564788-51fe26bd-4020-4399-a1f8-a160964cf63d.jpg)

**Comment by dottorblaster** [comment]
@lee-martin almighty Product Owner, shall we replace that with another one?

**Comment by stefanotorresi** [comment]
@dottorblaster no need to ask for permission. If you agree with Zao's feedback, go right ahead and find a better alternative. ;)

I agree with him, FWIW.

**Comment by dottorblaster** [comment]
We could apply the `policy` icon, but it has another magnifying glass inside :sweat_smile: Otherwise, we can use the `shield` one.

WDYT?

https://eos-icons.com/?iconName=policy

**Comment by stefanotorresi** [comment]
Since this icon is about just the license, what about [`article`][(https://eos-icons.com/?iconName=article) or [`assignment`][(https://eos-icons.com/?iconName=assignment)?

**Comment by dottorblaster** [comment]
`assignment` looks fine to me, thanks!
