### ISSUE TITLE
Filters tags added at page of Hosts shows up on page Peacemake Clusters

### ISSUE THREAD

**Issue by Zaoliang** [trento-project/trento#544]
trento server v0.6.0
QA Server: http://20.67.108.123/

Add some tags at first for Filters on page Hosts and then switch to page Peacemaker Clusters.
Add some tags here and click later in field tags, tags added at page Hosts showing up now here. You can even select all of them. This is wrong and misleading.

See screenshots:
1. all tags showed up

![tags-1](https://user-images.githubusercontent.com/4113246/144884248-a80ca27c-09e5-441c-9513-1d9dbd5b1b7c.jpg)

2. can select all of them, 9 items selected

![tags-2](https://user-images.githubusercontent.com/4113246/144884440-d67c1527-e586-4e64-a62d-09e9d2a2c820.jpg)

**Comment by fabriziosestito** [comment]
@Zaoliang thanks for reporting this, it is already been addressed in an upcoming PR which just linked for reference
