### ISSUE TITLE
Duplicate database after unregistration and registration process

### ISSUE THREAD

**Issue by abravosuse** [trento-project/trento#573]
Trento version: v0.6.0
Trento environment: QA testing cycle 2
Description: following an issue with HANA system replication in the Trento testing environment, I had to unregister and register the HANA secondary database of one of the SAP systems. The cluster is now working fine but when I access the Trento console and go to the HANA Databases view, I see two databases with the same SID. One of them is obsolete, the other one is up to date. I have restarted the Trento agents in both nodes but that didn't fix the issue. See attached screenshot.

![image](https://user-images.githubusercontent.com/91731013/145978081-018e98c6-ba9f-4e28-8c47-07a1fbc1e803.png)

**Comment by fabriziosestito** [comment]
Need to be confirmed on the `rolling` version, it might be already fixed

**Comment by abravosuse** [comment]
v0.7.0: Same issue. HANA database listed twice after un_register even followed by registration with force_full_replica option:

![image](https://user-images.githubusercontent.com/91731013/146776870-028a28ed-4159-4ba9-8bdd-7471026b2c97.png)
