### ISSUE TITLE
Obsolete database info in Hosts detail view after un_registration

### ISSUE THREAD

**Issue by abravosuse** [trento-project/trento#576]
Trento version: v0.6.0
Trento environment: QA testing cycle 2
Description: following an issue with HANA system replication in the Trento testing environment, I had to unregister and register the HANA secondary database of one of the SAP systems. The cluster is now working fine but when I access the Trento console, go to the Hosts view and click on the secondary node, I see that the all registered instance is still showing with the hdbdaemon process Stopped (along the processes of the newly registered instance which are all Running). See screenshot:

![image](https://user-images.githubusercontent.com/91731013/145992888-c77d3af7-53d6-4503-8e5d-5899442af88e.png)

**Comment by fabriziosestito** [comment]
Need to be confirmed on the rolling version, it might be already fixed or the behavior could be different

See: #538

**Comment by abravosuse** [comment]
v0.7.0: HANA instance listed twice in Host details view after un_register event, followed by registration with full_force_replica option:

![image](https://user-images.githubusercontent.com/91731013/146777261-d0daf3fa-2583-47a2-a4b9-2b00a393a8c5.png)

**Comment by abravosuse** [comment]
Hi @fabriziosestito. I think we might have to double check this one. As you told me by slack that it would fix existing duplications, I went ahead and updated Trento Server to the latest rolling version (v0.7.1+git.dev12.1640105501.52d1ac6) as well as all the agents in env2 and env3 hosts (env1 hosts are down).  As result all NetWeaver and HANA instances have disappeared from the console, except for one in host vmnwqas04:

![image](https://user-images.githubusercontent.com/91731013/146974378-9a9f7dc1-1aa3-440a-8a99-4b3d02d2ab05.png)

![image](https://user-images.githubusercontent.com/91731013/146974445-e63f38ec-ec5c-4ba6-b111-ed72deb16b63.png)

**Comment by fabriziosestito** [comment]
@abravosuse sorry my bad, fixed and merged in #645

**Comment by abravosuse** [comment]
@fabriziosestito all back to normal with 0.7.1+git.dev15.1640110639.2081b1e. Thank you!

![image](https://user-images.githubusercontent.com/91731013/146983338-a21145e0-696d-4f54-9ff9-cdba44286166.png)

![image](https://user-images.githubusercontent.com/91731013/146983394-63e720b7-e803-4872-838d-db983d9e5e68.png)
