### ISSUE TITLE
All hosts got red icon '!'  regardless trento agent is running 

### ISSUE THREAD

**Issue by Zaoliang** [trento-project/trento#596]
Testing 3nd round for v0.6.0
trento server: v0.6.0+git.dev282.1639671445.67f8ba5

Go to QA trento server:  http://20.126.10.94/hosts

I see some red '!' icon at left side of hosts. Few minutes later I reload the page, each host got red icon '!'. I checked hosts of SAP System, some show trento agent is not running and some show agent is running.

If I click a host with red '!', I got some times at once service unavailable, for example: http://20.126.10.94/hosts/946d2157-c764-53a3-8f51-78b5758fc107

If I can open the page for this host, I see Agent status 'running'. 
Now go back page Hosts and reload the page, every host got green icon and then some hosts becomes red again. This is confusing.

**Comment by fabriziosestito** [comment]
@Zaoliang the green/red status reports the agent heartbeat and it is updated with every few seconds.
If some agent was not reporting and then reporting back again, the behavior you experienced it is expected.

It can be manually tested by stopping an agent on any of the machines, waiting few seconds, check the status which has to be red, and then starting the agent again.

**Comment by fabriziosestito** [comment]
Closed by #599
