### ISSUE TITLE
Pacemaker Clusters -  Health status always has value '0' for Passing, Warning, Critical all the time

### ISSUE THREAD

**Issue by Zaoliang** [trento-project/trento#601]
Testing 3rd round 
Server version: v0.6.0+git.dev293.1639737346.f1029ae

Go to QA server: http://20.126.10.94/clusters

It seems no changes or no detection for cluster at all if it shows all the time '0' for Passing, Warning Critical. At least one has different value than '0'.

![image](https://user-images.githubusercontent.com/4113246/146550560-8abb6cc9-952e-4b2d-9649-a9312194d50a.png)

If I open http://20.126.10.94/clusters/c5a97846783e585890ef9cea7628aa41 , I got an error displayed (is this English OH NOES ? :) )

![image](https://user-images.githubusercontent.com/4113246/146550167-57f88bbf-eded-4c4e-a4e9-90dc46c8c3f6.png)

**Comment by fabriziosestito** [comment]
@nelsonkopliku I was able to reproduce is, it happens when the checks list is empty. Maybe we return null instead of an empty list and react breaks
Investigating it.

**Comment by rtorrero** [comment]
The "OH NOES" is not English, it's Biancalanan and we should keep it 😄
