### ISSUE TITLE
Pacemaker Clusters details - Health - 'Show check results' is misleading

### ISSUE THREAD

**Issue by Zaoliang** [trento-project/trento#605]
Testing 3rd round
Server version: v0.6.0+git.dev293.1639737346.f1029ae

Go to QA server: http://20.126.10.94/clusters

Click and open a Cluster Id of hana_cluster, for example http://20.126.10.94/clusters/9e1e67ec691ecbf092739a4d5945c16a
Click button under Health 'Show check details', it opens a pop-up 'Health Details' and click any of displayed item, it leads to Settings - Checks catalog.

Well, I expected actually some detailed information about Cluster, not links of documentation about checks catalog.

**Comment by abravosuse** [comment]
v0.7.0: same behavior

I guess that for checks showing in Warning or Critical status, in addition to the link to the corresponding Checks Catalog section, an explanation on why the status is such should be given. For example, for cluster HDP in our test environment,  if I see that the SDB watchdog timeout check is critical status:

![image](https://user-images.githubusercontent.com/91731013/146684296-25a37ae6-3a8e-4220-bcf5-795ef442d726.png)

When I click on the link I would expect the out of command `sudo sbd -d /dev/disk/by-id/scsi-SLIO-ORG_IBLOCK_8adcc949-aa30-4dd3-95f9-3903692f91f4 dump` to be shown, highlighting the value for the watchdog timeout (which is this case is 5).

![image](https://user-images.githubusercontent.com/91731013/146684659-498b42d9-3228-44ad-89da-fb7bdaf84365.png)

Further more, but this is part of a broader discussion, the information in the Checks Catalog itself must be reviewed carefully.

In this particular case, it says that it should be set to 60 seconds as recommended on the best practices.

But the reference given, https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker#set-up-sbd-device, doesn't say anything about this particular parameter/value. It is not clear where this recommendation is coming from or how to perform the change.

**Comment by arbulu89** [comment]
Hi @abravosuse and @Zaoliang . This model visualization is totally intentional.
What you ask about showing the output of a command there is really difficult to be implemented by now, and it has been avoided.
Maybe we could implement it in the future. It was already in our radar.
I think this ticket is product design oriented and we should debate it in other planning/product design moments

**Comment by abravosuse** [comment]
Agreed @arbulu89. I have added it as a potential enhancement to be discussed in a broader framework. Issue can be closed.
