### ISSUE TITLE
Cloud provider name is missing from the host's Cloud Detail section

### ISSUE THREAD

**Issue by stefanotorresi** [trento-project/trento#690]
I would expect to see something like "Provider: Azure" somewhere there.

![Screenshot from 2022-01-11 12-07-40](https://user-images.githubusercontent.com/2952427/148931924-8a86ce4d-d13a-42cd-a8a1-2b863442cbfe.png)

 I think it was present in the past but we might have removed it with the most recent layout.

**Comment by dottorblaster** [comment]
Fair enough, I'll take a look as soon as possible.
