### ISSUE TITLE
Health overview should give information about all the hosts

### ISSUE THREAD

**Issue by nelsonkopliku** [trento-project/trento#691]
In the Hosts Overview (`/hosts`) the health container is showing statuses for the currently shown items.
So in a cluster with more hosts that we're currently showing, we have a partial information.

Example: cluster with 27 hosts
When we visit the Hosts Overview we should see the status of all the 27, not only the 10 items shown at the moment.

![image](https://user-images.githubusercontent.com/8167114/148975946-8df34e0e-fbee-4bf4-acb8-6e69e148f9ca.png)

If we increase the pagination limit to show all the hosts we see the correct health overview

![image](https://user-images.githubusercontent.com/8167114/148976571-d4742204-60fa-4773-8cdc-13489b4aa9a4.png)

**Comment by abravosuse** [comment]
Good catch @nelsonkopliku. I meant to report this after round 3 but forgot doing it. Yes, the health status section should reflect all registered hosts, regardless how many are shown in the page.

**Comment by arbulu89** [comment]
Hey @nelsonkopliku and @abravosuse 
Question about this. What about when we apply filters?
Should only show the numbers with the applied filters or still the total number?
I would say the filtered numbers, right?

**Comment by nelsonkopliku** [comment]
@arbulu89 I think it should always be the total, no matter what pagination limit or filter has been applied.
As a user I'd find this more helpful (but I am not a user :trollface: )

**Comment by abravosuse** [comment]
Agreed @arbulu89. When you apply filters, the number of systems in the health section and the number of total items should reflect the number of systems that match that filter.
