### ISSUE TITLE
Settings button missing in Pacemaker Clusters details view

### ISSUE THREAD

**Issue by abravosuse** [trento-project/trento#705]
Trento favor: premium
Server version: v0.7.1+git.dev42.1640084952.33229fc

The settings button is missing in the Pacemaker Clusters details view (e.g. http://20.126.33.235/clusters/04b8f8c21f9fd8991224478e8c4362f8):

![image](https://user-images.githubusercontent.com/91731013/149511419-b0cd7ece-0dff-4c88-82bc-db520f16230d.png)

**Comment by arbulu89** [comment]
Most probably (99% sure) related to https://github.com/trento-project/trento/issues/706

**Comment by dottorblaster** [comment]
Agreed!

**Comment by abravosuse** [comment]
Fixed in v0.8.1. Issue can be closed.
