### ISSUE TITLE
use `path.Join()` to interpolate KV store keys.

### ISSUE THREAD

**Issue by stefanotorresi** [trento-project/trento#76]
you can use `path.Join()` instead of `fmt.Sprintf()` so that we don't have to care about ending or leading slashes.

_Originally posted by @stefanotorresi in https://github.com/trento-project/trento/pull/71#discussion_r644606381_

**Comment by arbulu89** [comment]
Fixed at: https://github.com/trento-project/trento/pull/72/commits/5ed4c1ea0cf56f1528f9103343b63b75cdc862d2
