### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by wtmpx** [trento-project/trento#835]
Dears, 
When I try to use existing flag the Trento GUI suggest it,, when clicking on it ; the tag doesn't set.

E.g. I have a host with tag: ScaleUp ,,, when trying to use the tag with another host, writing "Sc" the GUI suggest ScaleUp; when clicking on it, the tag will be "Sc" 

Thanks

**Comment by stefanotorresi** [comment]
Thanks for reporting this. The issue should no longer apply since the web was reimplemented in https://github.com/trento-project/web.
