### ISSUE TITLE
Identify and store cluster entries with unique ID in the KV store

### ISSUE THREAD

**Issue by arbulu89** [trento-project/trento#88]
By now the cluster entries are identified by the cluster name. The cluster name is not unique at all, and actually, it is not even mandatory to have, it is yet another attribute of the cluster.

By now, we store the data as:

`trento/v0/cluster/$clustername/...`

We need to change this $clustername by something unique. The cluster doesn't have any widely unique attribute unfortunately, but we could use the corosync authentication key for that (get the md5sum of it). This file is located at `/etc/corosync/auth`, or maybe create some other combination of data to create the unique permanent id of the cluster.

After that, we would need to store the cluster name as well, to use it the frontend, and if it doesn't exist, use some autogenerated name (`london`, `paris`, you know, these kind of names...).

The frontend needs to use this name in all of the visualization, and take care to do something if 2 cluster with the same name are available (maybe add something like `hana-cluster*1`, `hana-cluster*2`).

Finally, we need to manage the `ha-cluster` metadata tags as well, to use the proper tag in consul filterings.

**Comment by arbulu89** [comment]
As a comment, the cluster name is just an attribute: `cib-bootstrap-options-cluster-name`.

**Comment by rtorrero** [comment]
Thanks @arbulu89 , I already started working on this and should have something soon

**Comment by arbulu89** [comment]
Closing as it is implemented (at least the 1st iteration) at https://github.com/trento-project/trento/pull/114
