### ISSUE TITLE
trento-agent installation -- colorful console output is difficult to read

### ISSUE THREAD

**Issue by pirat013** [trento-project/trento#886]
Using a terminal with a white background makes it difficult to read the output of the trento-agent installation:
(the bold line is grey)
```
# ./install-agent.sh 
Installing trento-agent...
Please provide an ssh address for the agent: 10.0.0.119
Please provide the server IP: 10.0.0.121
* Adding Trento repository: https://download.opensuse.org/repositories/devel:/sap:/trento/15.3/.
* Installing trento
* Generating trento-agent config...
Done.
```
**Now you can start trento-agent with: systemctl start trento-agent**
```
Please make sure the server is running before starting the agent.
```

**Comment by stefanotorresi** [comment]
we're planning to dial down our efforts in the installation scripts, which are not really needed anymore as we made RPM packages and helm charts more easily available.
