### ISSUE TITLE
Clarify difference between "Checkers" and "Discovery" in the hosts detail UI

### ISSUE THREAD

**Issue by rtorrero** [trento-project/trento#89]
When clicking on the details for a host, the list of Checks for the host is displayed. In this list we see e.g.:

"HA Cluster Discovery" with the description "Collects details about the HA Cluster components running on this node" and status "passing". This item is not clickable nor provides any additional details about what it did or what the result of the check was.

We also have e.g. "HA config checker" which on the other hand has detailed information on the checks it did and allows to click it to give a lot of details on the checks.

See:
![checks](https://user-images.githubusercontent.com/2668401/121690669-09af1c00-cabe-11eb-99a6-29825d19ee4e.png)

From this I assume that a "Discovery" is something very simple that just implements the functionality to determine the role(s) of each host, while a "Checker" is actually checking specific aspects of the host, depending on it's role. Could we maybe separate these or make it at least more understandable from the UI so that the users knows what to expect from each checker?

**Comment by stefanotorresi** [comment]
I totally agree that we should separate these.
I was never a fan of registering Consul health checks for the discovery loops, to be honest. Currently we don't even handle the failure of such checks very well.

**Comment by arbulu89** [comment]
Re-opened in: https://github.com/trento-project/trento/issues/208
