### ISSUE TITLE
32CFC6 -- Corosync is running with at least 2 rings -> reports warning

### ISSUE THREAD

**Issue by pirat013** [trento-project/trento#891]
The check is looking for ttl of the interface:

`corosync-cmapctl | grep totem.interface\\..*\.ttl | wc -l
`
looking in the documentation it explains it like this:
ttl

This specifies the Time To Live (TTL). If you run your cluster on a routed network then the default of "1" will be too small. This option provides a way to increase this up to 255. The valid range is 0..255. Note that this is only valid on multicast transport types. 

Would suggest to grep for **totem.interface\\..*\.bindnetaddr** instead.

**Comment by fmherschel** [comment]
As discussed that's the issue I might help with the scanner. Searching for TTL is indeed not helpful here.

**Comment by stefanotorresi** [comment]
implemented in https://github.com/trento-project/runner/pull/38
